# Generated by Django 3.2.4 on 2021-06-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactFirstName', models.CharField(max_length=30)),
                ('contactLastName', models.CharField(max_length=30)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('contactPhoneNumber', models.CharField(max_length=12)),
            ],
        ),
    ]
